ALTER TABLE products
  ADD CONSTRAINT unique_products_idname
  UNIQUE (idname);


\d products;


INSERT INTO public.products (idname, availability, is_one_size, productname, productcolor, productprice, desclong, comp_care, pic1, pic2, pic3, pic4, pic5, pic6, pic7, pic8, pic9, name_pl,  desc_pl,  composition_and_care_pl) VALUES
   (
     'nolia-dustpink',
     'Available',
     false,
     'Nolia Woven Dress',
     'Dust Pink',
     215,
     '<div class="ju">NOLIA is beautifully flowy yet romantic, a perfect dress from cooler summer days. Wear it at times when you want to look beautiful and chic with minimal effort. Contemporary design is complemented by beautiful details, it has elbow length sleeves and two hidden pockets. Dress it up with warmer knit and keep wearing it through the fall. <br /> Incredibly pleasant to the skin NOLIA, made with care in Poland from the fibers of the lotus flower and organic cotton. <br /><br /> NOLIA dress is made to order and may take 1-2 weeks to be hand sewn with care in Poland.</div>',
     '<div class="ju">95% cotton and 5% lotus flower beautifully woven fabric, using natural dyes, not certified. Unique and hand-woven by women in Cambodia. Wash on a gentle cycle at 30 degrees Celsius, iron on a low level and do not tumble dry. Our fabrics are durable and do not require dry cleaning.</div>',
     'mynawebshop-pinkdress-1.jpg',
     'mynawebshop-pinkdress-2.jpg',
     'mynawebshop-pinkdress-3.jpg',
     'mynawebshop-pinkdress-4.jpg',
     NULL,
     NULL,
     NULL,
     NULL,
     NULL,
     'NOLIA Sukienka',
     '<div class="ju">NOLIA to przepięknie zwiewna a zarazem romantyczna sukienka idealna na chłodniejsze letnie dni. Idealna, kiedy chcesz wyglądać pięknie i szykownie przy minimalnym wysiłku. Współczesny krój dopełniają piękne detale, rękawy sięgające do łokci z malymi rozporkami oraz dwie ukryte kieszenie.  Niesamowicie przyjemna dla skóry NOLIA, wykonana z dbałością w Polsce z włókien kwiata lotus i bawełny organicznej. <br /><br /> NOLIA sukienka jest szyta na zamówienie i może zająć 1-2 tygodnie, zanim zostanie ręcznie uszyta z dbałoscią w Polsce.</div>',
     '<div class="ju">95% bawełna i 5% włókna kwiata lotusa, pięknie tkana tkanina, przy użyciu naturalnych barwników, nie atestowana. Unikalne i ręcznie tkane przez kobiety w Kambodży. Prać w delikatnym cyklu w 30 stopniach Celsjusza, prasować na niskim poziomie i nie suszyć w suszarce. Nasze tkaniny są trwałe i nie wymagają czyszczenia na sucho.</div>'
   ),
   (
     'aster-green',
     'Available',
     false,
     'Aster Woven Culotte Pants',
     'Summer Green',
     109,
     '<div class="ju">Aster will be the most comfortable culotte pants you''ll ever own, we promise you. They are high wasted and flattering fit, with two hidden pockets and with a bit of elastic for extra cosy feeling around your waist. Dress them up or down with a beautiful top, wherever the inspiration takes you. Handmade with care in Poland from the incredibly pleasant to the skin fibers of lotus flower and organic cotton.<br /><br />ASTER culottes are made to order and may take 1-2 weeks to be hand sewn with care in Poland.</div>',
     '<div class="ju">95% cotton and 5% lotus flower beautifully woven fabric, using natural dyes, not certified. Unique and hand-woven by women in Cambodia. Wash on a gentle cycle at 30 degrees Celsius, iron on a low level and do not tumble dry. Our fabrics are durable and do not require dry cleaning.</div>',
     'mynawebshop-greenpants-1.jpg',
     'mynawebshop-greenpants-2.jpg',
     'mynawebshop-greenpants-3.jpg',
     'mynawebshop-greenpants-4.jpg',
     NULL,
     NULL,
     NULL,
     NULL,
     NULL,
     'ASTER Kuloty',
     '<div class="ju">Aster będą najwygodniejszymi spodniami, jakie kiedykolwiek posiadasz, obiecujemy. Mają wysoki stan i podkreślają sylwetkę krój, z dwiema ukrytymi kieszeniami i odrobiną gumki, aby zapewnić dodatkowe uczucie przytulności w talii. Dopasuj je do swojej wygody, gdziekolwiek zaprowadzi Cię inspiracja. Wykonane z dbałością w Polsce z niesamowicie przyjemnych dla skóry włókien kwiata lotusa oraz bawełny organicznej.<br /><br />ASTER spodnie są szyte na zamówienie i może zająć 1-2 tygodnie, zanim zostanie ręcznie uszyta z dbałoscią w Polsce.</div>',
     '<div class="ju">95% bawełna i 5% włókna kwiata lotusa, pięknie tkana tkanina, przy użyciu naturalnych barwników, nie atestowana. Unikalne i ręcznie tkane przez kobiety w Kambodży. Prać w delikatnym cyklu w 30 stopniach Celsjusza, prasować na niskim poziomie i nie suszyć w suszarce. Nasze tkaniny są trwałe i nie wymagają czyszczenia na sucho.</div>'
   ),
   (
     'calla-cream',
     'Available',
     false,
     'Calla Denim Pants',
     'Satin Cream',
     149,
     '<div class="ju">Our CALLA jeans have a straight cut with a high waist. Beautifully tailored, classic and stylish, without elastin, like it used to be. Every woman needs white jeans in her wardrobe because it''s been a timeless and classic style for centuries! The timeless and simple cut of CALLA will change your style from a relaxed to even elegant style that you create for yourself for years. Made with care in Poland.<br /><br /> CALLA are made to order and will take 1-2 weeks to be handcrafted in Poland and shipped with care.</div>',
     '<div class="ju">100% organic cotton woven denim, Anbau (kbA) certified, made in Turkey. Wash in a regular cycle at 30 degrees Celsius, iron on a low level and do not tumble dry. Our fabrics are durable and do not require dry cleaning.</div>',
     'mynawebshop-whitejeans-1.jpg',
     'mynawebshop-whitejeans-2.jpg',
     'mynawebshop-whitejeans-3.jpg',
     'mynawebshop-whitejeans-4.jpg',
     NULL,
     NULL,
     NULL,
     NULL,
     NULL,
     'Calla Spodnie Dżinsowe',
     '<div class="ju">Nasze dżinsy CALLA mają prosty krój z wysokim stanem. Pieknie skrojone, klasyczne i szykowne, bez elastyny jak dawniej. Każda kobieta potrzebuje białych dżinsów w swojej szafie bo to przeciez ponadczasowy i klasyczny styl od wieków! Ponadczasowy i prosty krój CALLA zmieni Twój styl z relaksowanego do nawet eleganckiego stylu jaki stworzysz dla siebie na lata. Wykonane z dbałością w Polsce.<br /><br /> CALLA są  szyte na zamówienie i zajmie 1-2 tygodni, zanim zostana ręcznie wykonane w Polsce i wysłane z należytą starannością.</div>',
     '<div class="ju">100% tkany denim z bawełny organicznej, z certyfikatem kontrolliert biologischer Anbau (kbA), wyprodukowany w Turcji. Pierz w regularnym cyklu w 30 stopniach Celsjusza, prasuj na niskim poziomie i nie susz w suszarce. Nasze tkaniny są trwałe i nie wymagają czyszczenia na sucho.</div>'
   ),
   (
     'ivy-cream',
     'Available',
     false,
     'Ivy Knitted Jersey Top',
     'Satin Cream',
     69,
     '<div class="ju">Beautifully designed for your comfort and a relaxed yet elegant look. IVY is perfect for warm and sunny days and for winter layers with classic and timeless combination. It goes great with jeans, a skirt or our favorite pair of ASTER coullete trousers. Made with care in Poland from organic cotton and hemp. <br /><br /> IVY is made to order and will take 1-2 weeks to be handcrafted in Poland and shipped with proper care.</div>',
     '<div class="ju">55% organic cotton and 45% hemp knit, dyed with GOTS-certified dyes, not certified, made in China (organic cotton grown in Turkey). Wash in a regular cycle at 30 degrees Celsius, iron on a low level and do not tumble dry. Our fabrics are durable and do not require dry cleaning.</div>',
     'mynawebshop-whitetshirt-1.jpg',
     'mynawebshop-whitetshirt-2.jpg',
     'mynawebshop-whitetshirt-3.jpg',
     'mynawebshop-whitetshirt-4.jpg',
     NULL,
     NULL,
     NULL,
     NULL,
     NULL,
     'IVY Koszulka',
     '<div class="ju">Pięknie zaprojektowana dla Twojej wygody i zrelaksowanego, ale również eleganckiego wyglądu. GEA jest idealna na ciepłe dni oraz pod zimowe warstwy zestawu w klasycznym i ponadczasowym połączeniu.  Świetnie komponuje się z dżinsami, spódnicą lub naszą ulubioną parą spodni typu coullete ASTER. Wykonana z dbałością w Polsce z organicznej bawełny i konopii. <br /><br /> Gea jest szyta na zamówienie i zajmie 1-2 tygodni, zanim zostanie ręcznie wykonany w Polsce i wysłany z należytą starannością.</div>',
     '<div class="ju">55% bawełna organiczna i 45% dzianina konopna, barwiona przy użyciu barwników z certyfikatem GOTS, niecertyfikowana, wyprodukowana w Chinach (bawełna organiczna uprawiana w Turcji). Pierz w regularnym cyklu w 30 stopniach Celsjusza, prasuj na niskim poziomie i nie susz w suszarce. Nasze tkaniny są trwałe i nie wymagają czyszczenia na sucho.</div>'
   ),
   (
     'gea-cream',
     'Available',
     false,
     'Gea Knitted Jersey Top',
     'Satin Cream',
     69,
     '<div class="ju">Since every woman needs a white T-shirt, we created GEA to give your collection a contemporary twist. A beautiful and classic V-neck design that goes great with your favorite jeans or a skirt for a more feminine look. Made with care in Poland from organic cotton and hemp. <br /><br /> GEA is made to order and will take 1-2 weeks to be handcrafted in Poland and shipped with due care.</div>',
     '<div class="ju">55% organic cotton and 45% hemp knit, dyed with GOTS-certified dyes, made in China (organic cotton grown in Turkey). Wash in a regular cycle at 30 degrees Celsius, iron on a low level and do not tumble dry. Our fabrics are durable and do not require dry cleaning.</div>',
     'mynawebshop-whitetop-1.jpg',
     'mynawebshop-whitetop-2.jpg',
     'mynawebshop-whitetop-3.jpg',
     'mynawebshop-whitetop-4.jpg',
     NULL,
     NULL,
     NULL,
     NULL,
     NULL,
     'GEA Koszulka',
     '<div class="ju">Ponieważ każda kobieta potrzebuje białej koszulki, stworzyliśmy GEA, aby nadać Twojej kolekcji współczesnego charakteru. Piękny i klasyczny fason z dekoltem w szpic, świetnie komponuje się z Twoimi ulubionymi dżinsami lub spódnicą dla bardziej kobiecego wyglądu. Wykonana z dbałością w Polsce z bawełny organicznej i konopi. <br /><br /> GEA jest szyta na zamówienie i zajmie 1-2 tygodni, zanim zostanie ręcznie wykonany w Polsce i wysłany z należytą starannością.</div>',
     '<div class="ju">55% bawełna organiczna i 45% dzianina konopna, barwiona przy użyciu barwników z certyfikatem GOTS, wyprodukowana w Chinach (bawełna organiczna uprawiana w Turcji). Pierz w regularnym cyklu w 30 stopniach Celsjusza, prasuj na niskim poziomie i nie susz w suszarce. Nasze tkaniny są trwałe i nie wymagają czyszczenia na sucho.</div>'
   ),
   (
     'alyss-dress',
     'Available',
     false,
     'ALYSS Tencel Woven Dress',
     'Shadow Sand',
     169,
     '<div class="ju">ALYSS impresses with its sensual elegance, perfect for a celebration, date or when you feel for a relaxed and elegant duo. A truly feminine and timeless design, finished with beautiful details and recycled shell buttons for an eye-catching rainbow effect. It works perfectly with both high boots and white sneakers, we tried both and enjoyed it a lot. Made with care in Poland from wood cellulose, known for its delicacy and pleasant touch. <br /><br /> ALYSS is made to order and may take 1-2 weeks to be hand sewn with care in Poland.</div>',
     '<div class="ju">100% Tencel, wood cellulose, dyed with GOTS certified dyes with GOTS certificate, made in Turkey. Wash on a gentle cycle at 30 degrees, iron on a low level and do not tumble dry. Our fabrics are durable and do not require dry cleaning. Iron inside out.</div>',
     'mynawebshop-alyssdress-2.jpg',
     'mynawebshop-alyssdress-3.jpg',
     'mynawebshop-alyssdress-4.jpg',
     'mynawebshop-alyssdress-5.jpg',
     NULL,
     NULL,
     NULL,
     NULL,
     NULL,
     'ALYSS Sukienka',
     '<div class="ju">ALYSS zachwyca zmysłową elegancją, idealna na uroczystość,  randkę lub kiedy masz ochote na zrelaksowany i elegancki duet. Prawdziwie kobiecy i ponadczasowy fason, wykończony pięknymi detalami i guzikami z muszli z recyklingu, tworzącymi przyciągający wzrok efektu tęczy. Działa idealnie zarówno z wysokimi butami, jak i białymi tenisówkami, próbowaliśmy obu i bardzo nam się podobało. Wykonana z dbałością w Polsce z celulozy drzewnej, znanej z delikatnosci i przyjemnego dotyku. <br /><br /> ALYSS jest szyta na zamówienie i może zająć 1-2 tygodnie, zanim zostanie ręcznie uszyta z dbałoscią w Polsce.</div>',
     '<div class="ju">100% tencel, celuloza drzewna, barwiony przy użyciu barwników z certyfikatem GOTS z certyfikatem GOTS, wyprodukowany w Turcji. Prać na delikatnym cyklu w 30 stopniach, prasować na niskim poziomie i nie suszyć w suszarce. Nasze tkaniny są trwałe i nie wymagają czyszczenia na sucho. Prasowac na lewej stronie.</div>'
   ),
   (
     'magna-scarf',
     'Available',
     true,
     'MAGNA Woven Scarf',
     'Dust Pink',
     95,
     '<div class="ju">MAGNA shawl is the softest to the touch lotus fiber that provides warm through out autumn and summer evenings. Finished by hand with embroidery imitating a lotus flower. Combine it with NOLA for a unique monochrome look. Made with care in Poland. <br /><br /> MAGNA shawl is sewn and embroidered to order and may take 1-2 weeks to be hand-sewn with care in Poland.</div>',
     '<div class="ju">95% cotton and 5% lotus flower beautifully woven fabric, using natural dyes, not certified. Unique and hand-woven by women in Cambodia. Wash on a gentle cycle at 30 degrees Celsius, iron on a low level and do not tumble dry. Our fabrics are durable and do not require dry cleaning.</div>',
     'mynawebshop-magnascarf-2.jpg',
     'mynawebshop-magnascarf-1.jpg',
     'mynawebshop-magnascarf-3.jpg',
     'mynawebshop-magnascarf-4.jpg',
     NULL,
     NULL,
     NULL,
     NULL,
     NULL,
     'MAGNA Szalik',
     '<div class="ju">Szal MAGNA to najdelikatniejsze w dotyku włókno lotosu, które zapewnia ciepło przez całą jesień i letnie wieczory. Wykończona ręcznie haftem imitujący kwiat lotusu. Połącz go z NOLIĄ, aby uzyskać wyjątkowy, monochromatyczny wygląd. Wykonany z dbałością w Polsce. <br /><br /> MAGNA szal jest szyty i haftowany na zamówienie i może zająć 1-2 tygodnie, zanim zostanie ręcznie uszyta z dbałoscią w Polsce.</div>',
     '<div class="ju">95% bawełna i 5% włókna kwiata lotusa, pięknie tkana tkanina, przy użyciu naturalnych barwników, nie atestowana. Unikalne i ręcznie tkane przez kobiety w Kambodży. Prać w delikatnym cyklu w 30 stopniach Celsjusza, prasować na niskim poziomie i nie suszyć w suszarce. Nasze tkaniny są trwałe i nie wymagają czyszczenia na sucho.</div>'
   ),
   (
     'senna-skirt',
     'Available',
     false,
     'SENNA Skirt',
     'Summer Green',
     115,
     '<div class="ju">SENNA will be the most comfortable and pleasant skirt you''ll ever own, we promise you. It is high wasted and flattering, with two hidden pockets for more comfortable design and elegant look. Dress it up or down with a beautiful top, wherever the inspiration takes you. Made with care in Poland from the incredibly pleasant to the skin fibers of lotus flower and organic cotton. <br /><br /> SENNA skirt is made to order and may take 1-2 weeks to be hand sewn with care in Poland.</div>',
     '<div class="ju">95% cotton and 5% lotus flower beautifully woven fabric, using natural dyes, not certified. Unique and hand-woven by women in Cambodia. Wash on a gentle cycle at 30 degrees Celsius, iron on a low level and do not tumble dry. Our fabrics are durable and do not require dry cleaning.</div>',
     'senna-skirt-01.jpg',
     'senna-skirt-02.jpg',
     'senna-skirt-03.jpg',
     'senna-skirt-04.jpg',
     NULL,
     NULL,
     NULL,
     NULL,
     NULL,
     'SENNA Spódnica',
     '<div class="ju">SENNA będzie najbardziej wygodną i przyjemną spódnicą, jaką kiedykolwiek będziesz mieć, obiecujemy. Wysoki stan i ekologiczne guziki korozo tworzą przepękny ponadczasowy styl. Dodatkowo dwie ukryte kieszenie tworzą wygodny i elegancki wygląd. Dopasuj z klasyczna bluzka, gdziekolwiek zaprowadzi Cię inspiracja. Wykonana z dbałością w Polsce z niesamowicie przyjemnych dla skóry włókien kwiata lotus i bawełny organicznej. <br /><br /> SENNA spódnica jest szyta na zamówienie i może zająć 1-2 tygodnie, zanim zostanie ręcznie uszyta z dbałoscią w Polsce.</div>',
     '<div class="ju">95% bawełna i 5% kwiat lotosu pięknie tkana tkanina, przy użyciu naturalnych barwników, nie atestowana. Unikalne i ręcznie tkane przez kobiety w Kambodży. Prać w delikatnym cyklu w 30 stopniach Celsjusza, prasować na niskim poziomie i nie suszyć w suszarce. Nasze tkaniny są trwałe i nie wymagają czyszczenia na sucho.</div>'
   ),
   (
     'delphi-culottes',
     'Available',
     false,
     'DELPHI Culottes',
     'Shadow Sand',
     89,
     '<div class="ju">DELPHI is a high-wasted and extremely comfortable culotte. Perfect cut and velvety soft tencel fabric provide natural comfort. Tencel is made of cellulose fibers, quite versatile, soft and pleasant to the skin. Beautifully finished and timeless cut. Made with care in Poland. <br /><br /> DELPHI pants are made to order and may take 1-2 weeks to be hand sewn with care in Poland.</div>',
     '<div class="ju">100% Tencel, wood cellulose, dyed with GOTS certified dyes with GOTS certificate, made in Turkey. Wash on a gentle cycle at 30 degrees, iron on a low level and do not tumble dry. Our fabrics are durable and do not require dry cleaning. Iron inside out.</div>',
     'delphi-culottes-01.jpg',
     'delphi-culottes-02.jpg',
     'delphi-culottes-03.jpg',
     'delphi-culottes-04.jpg',
     NULL,
     NULL,
     NULL,
     NULL,
     NULL,
     'DELPHI Kuloty',
     '<div class="ju">DELPHI to kuloty z wysokim stanem i niezwykle wygodne. Idealny krój i aksamitnie delikatna tkanina tencel sprawia naturalny komfort . Tencel jest wykonany z włókien celulozowych, dość uniwersalnych, miękkich i przyjemnych dla skóry. Pięknie wykończony i ponadczasowy fason. Wykonane z dbałością w Polsce. <br /><br /> DELPHI spodnie są szyte na zamówienie i może zająć 1-2 tygodnie, zanim zostanie ręcznie uszyta z dbałoscią w Polsce.</div>',
     '<div class="ju">100% tencel, celuloza drzewna, barwiony przy użyciu barwników z certyfikatem GOTS z certyfikatem GOTS, wyprodukowany w Turcji. Prać na delikatnym cyklu w 30 stopniach, prasować na niskim poziomie i nie suszyć w suszarce. Nasze tkaniny są trwałe i nie wymagają czyszczenia na sucho. Prasowac na lewej stronie.</div>'
   ),
   (
     'reeva-denim-jacket',
     'Available',
     false,
     'REEVA Denim Jacket',
     'Satin Cream',
     139,
     '<div class="ju">Our REEVA denim jacket has a short and loose fit, perfect for high wasted jeans. Made of organic cotton and designed for lightness and an elegant timeless look. The mysteriously hidden and hand-painted details around the collar make this beautiful jacket insanely unique. Made with care in Poland. <br /><br /> REEVA is made to order and will take 1-2 weeks to be handcrafted in Poland and shipped with due care.</div>',
     '<div class="ju">100% organic cotton woven denim, GOTS certified, made in Turkey. Wash in a regular cycle at 30 degrees Celsius, iron on a low level and do not tumble dry. Our fabrics are durable and do not require dry cleaning.</div>',
     'reeva-denim-jacket-01.jpg',
     'reeva-denim-jacket-02.jpg',
     'reeva-denim-jacket-03.jpg',
     'reeva-denim-jacket-04.jpg',
     NULL,
     NULL,
     NULL,
     NULL,
     NULL,
     'REEVA Kurtka Dżinsowa',
     '<div class="ju">Nasza kurtka dżnsowa REEVA ma krótki i luźny krój, idealna do dżinsów z wysokim stanem. Uszyta z organicznej bawełny i zaprojektowana z myślą o lekkości i eleganckim ponadczasowym wyglądzie. Tajemniczo ukryte i ręcznie malowane detale wokół kołnierza sprawiają, że kurtka jest szalenie wyjątkowa. Wykonana z dbałością w Polsce. <br /><br /> REEVA jest szyta na zamówienie i zajmie 1-2 tygodni, zanim zostanie ręcznie wykonana w Polsce i wysłana z należytą starannością.</div>',
     '<div class="ju">100% tkany denim z bawełny organicznej, z certyfikatem kontrolliert biologischer Anbau (kbA), wyprodukowany w Turcji. Pierz w regularnym cyklu w 30 stopniach Celsjusza, prasuj na niskim poziomie i nie susz w suszarce. Nasze tkaniny są trwałe i nie wymagają czyszczenia na sucho.</div>'
   ),
   (
     'tilia-blouse',
     'Available',
     false,
     'TILIA Blouse',
     'Shadow Sand',
     89,
     '<div class="ju">When comfort meets a classic design, TILIA looks simple at first glance, but it''s a subtle beauty. Finished with an overlapping back that creates an amazing effect. Match with white jeans, a classic combination. Made with care in Poland from wood cellulose, known for its delicacy and pleasant touch. <br /><br /> TILIA is made to order and may take 1-2 weeks to be hand sewn with care in Poland.</div>',
     '<div class="ju">100% Tencel, wood cellulose, dyed with GOTS certified dyes with GOTS certificate, made in Turkey. Wash on a gentle cycle at 30 degrees, iron on a low level and do not tumble dry. Our fabrics are durable and do not require dry cleaning. Iron inside out.</div>',
     'tilia-blouse-01.jpg',
     'tilia-blouse-02.jpg',
     'tilia-blouse-03.jpg',
     'tilia-blouse-04.jpg',
     NULL,
     NULL,
     NULL,
     NULL,
     NULL,
     'TILIA bluzka',
     '<div class="ju">Kiedy komfort spotyka się z klasycznym wzorem, TILIA na pierwszy rzut oka wygląda prosto, ale jest to subtelne piękno. Wykończona nakładającym się tyłem, który tworzy niesamowity efekt. Dopasuj z białymi dżinsami, klasyczne połączenie. Wykonana z dbałością w Polsce z celulozy drzewnej, znanej z delikatnosci i przyjemnego dotyku. <br /><br /> TILIA jest szyta na zamówienie i może zająć 1-2 tygodnie, zanim zostanie ręcznie uszyta z dbałoscią w Polsce.</div>',
     '<div class="ju">100% tencel, celuloza drzewna, barwiony przy użyciu barwników z certyfikatem GOTS z certyfikatem GOTS, wyprodukowany w Turcji. Prać na delikatnym cyklu w 30 stopniach, prasować na niskim poziomie i nie suszyć w suszarce. Nasze tkaniny są trwałe i nie wymagają czyszczenia na sucho. Prasowac na lewej stronie.</div>'
   ),
   (
     'lola-oversized-shirt',
     'Available',
     false,
     'LOLA Oversize Shirt',
     'Satin White',
     149,
     '<div class="ju">Love&light collection. Classic and timeless design. Crafted from organic cotton cotton, certified by GOTS,  this shirt is cut for an oversize fit and elevated with a flattering longer back hem and hidden side pockets. Hand crafted embroidery hidden inside on the collar makes LOLA very special and unique. Fall in love with hidden details  - details only you know. Perfect with your favorite jeans, culottes or by itself for chilling around the house.</div>',
     '<div class="ju">100% organic cotton voile, GOTS certified, made in Turkey. Wash on delicate cycle at 30 celsius degrees, iron at low setting and do not tumble dry. Our fabrics are sustainable and do not require dry cleaning.</div>',
     'lola-oversized-shirt-01.jpg',
     'lola-oversized-shirt-02.jpg',
     'lola-oversized-shirt-03.jpg',
     'lola-oversized-shirt-04.jpg',
     NULL,
     NULL,
     NULL,
     NULL,
     NULL,
     'LOLA Koszula',
     '<div class="ju">Kolekcja Love & Light. Klasyczny i ponadczasowy design. Wykonana z bawełny organicznej, certyfikowanej przez GOTS, ta koszula ma oversize''owy krój i jest podwyższona z podkreślającym sylwetkę dłuższym tyłem i ukrytymi kieszeniami bocznymi. Ręcznie wykonany haft ukryty wewnątrz kołnierza sprawia, że ​​LOLA jest wyjątkowa i niepowtarzalna. Zakochaj się w ukrytych szczegółach - szczegóły znasz tylko Ty. Idealne do ulubionych dżinsów lub innych ulubionych spodni.</div>',
     '<div class="ju">100% woal z bawełny organicznej, z certyfikatem GOTS, wyprodukowany w Turcji. Prać w delikatnym cyklu w 30 stopniach, prasować na niskich obrotach i nie suszyć w suszarce.</div>'
   ),
   (
     'peri-blouse',
     'Available',
     false,
     'PERI Blouse',
     'Dusty Rose',
     155,
     '<div class="ju">Consciously Beautiful collection, crafted from organic cotton voile, certified by GOTS, this blouse is cut for loose and comfortable fit. Hand crafted embroidery creates special feeling. You can be sure that each blouse is never the same. Loose but still feminine design finished with front open slit with beautiful corozo button. Beautiful shade of dusty pink will brighten you up even on cloudy days. Pair it up with our Delphi culottes or Calla jeans.</div>',
     '<div class="ju">100% organic cotton voile, GOTS certified, made in Turkey. Wash on delicate cycle at 30 celsius degrees, iron at low setting and do not tumble dry. Our fabrics are sustainable and do not require dry cleaning.</div>',
     'peri-blouse-01.jpg',
     'peri-blouse-02.jpg',
     'peri-blouse-03.jpg',
     'peri-blouse-04.jpg',
     NULL,
     NULL,
     NULL,
     NULL,
     NULL,
     'PERI Bluzka',
     '<div class="ju">Z kolekcji Consciously Beautiful, wykonana z organicznego woalu bawełnianego, certyfikowana przez GOTS, ta bluzka jest skrojona na luźny i wygodny krój. Ręcznie wykonany haft dodaje wyjątkowości i dodatkowej wartości PERI. Możesz mieć pewność, że każda bluzka nigdy nie będzie taka sama. Luźny, ale nadal kobiecy fason wykończony rozcięciem z przodu z pięknym guzikiem corozo. Piękny odcień zgaszonego różu rozświetli Cię nawet w pochmurne dni. Połącz go z naszymi spodniami typu culottes Delphi lub dżinsami Calla.</div>',
     '<div class="ju">100% woal z bawełny organicznej, z certyfikatem GOTS, wyprodukowany w Turcji. Prać w delikatnym cyklu w 30 stopniach, prasować na niskich obrotach i nie suszyć w suszarce.</div>'
   ),
   (
     'flora-wrap-dress',
     'Available',
     false,
     'FLORA Wrap Dress',
     'Fresh Green',
     229,
     '<div class="ju">Consciously Beautiful collection, crafted from organic cotton and lotus fiber, made by supported women in Cambodia, this timeless wrap dress is cut for comfortable fit with only two coconut buttons at the front and loose fit sleeves. The biggest surprise of FLORA dress is two hidden side pockets. Who is looking for a dress with pockets? So rare, but we didn’t forget about this important detail. Extremely easy to wear our FLORA dress will keep you warm at winter and cool at warm weather thanks to amazing properties of lotus fiber.</div>',
     '<div class="ju">95% cotton and 5% lotus flower beautifully woven fabric, using natural dyes, not certified. Unique and hand-woven by women in Cambodia. Wash on a gentle cycle at 30 degrees Celsius, iron on a low level and do not tumble dry. Our fabrics are durable and do not require dry cleaning.</div>',
     'flora-dress-01.jpg',
     'flora-dress-02.jpg',
     'flora-dress-03.jpg',
     'flora-dress-04.jpg',
     NULL,
     NULL,
     NULL,
     NULL,
     NULL,
     'FLORA Sukienka Zakładana',
     '<div class="ju">Z kolekcji Consciously beautiful, wykonana z organicznej bawełny i włókien lotosu, stworzona przez wspierane kobiety w Kambodży, ta ponadczasowa sukienka kopertowa jest dopasowana do wygodnego kroju, z tylko dwoma kokosowymi guzikami z przodu i luźnymi rękawami. Największą niespodzianką sukienki FLORA są dwie ukryte boczne kieszenie. Kto szuka sukienki z kieszeniami? Tak rzadkie, ale nie zapomnieliśmy o tym ważnym szczególe. Niezwykle łatwa w noszeniu nasza sukienka FLORA zapewni Ci ciepło zimą i chłód w ciepłe dni dzięki niesamowitym właściwościom włókna lotosu.</div>',
     '<div class="ju">95% bawełna i 5% włókna kwiata lotusa, pięknie tkana tkanina, przy użyciu naturalnych barwników, nie atestowana. Unikalne i ręcznie tkane przez kobiety w Kambodży. Prać w delikatnym cyklu w 30 stopniach Celsjusza, prasować na niskim poziomie i nie suszyć w suszarce. Nasze tkaniny są trwałe i nie wymagają czyszczenia na sucho.</div>'
   ),
   (
     'marigold-trench-coat',
     'Available',
     false,
     'MARIGOLD Trench Coat',
     'Shadow Sand',
     215,
     '<div class="ju">Consciously Beautiful collection, timeless and classic design with attention to hidden details inside this beautifully crafted trench coat. Made with tencel fabric, the softest touch will make you always comfortable. Sustainable coconut button perfectly look with the total look. Transitional design of MARIGOLD trench coat will be handy in uncertain windy weather condition. A classic piece never goes out of style, right?</div>',
     '<div class="ju">100% Tencel, wood cellulose, dyed with GOTS certified dyes with GOTS certificate, made in Turkey. Wash on a gentle cycle at 30 degrees, iron on a low level and do not tumble dry. Our fabrics are durable and do not require dry cleaning. Iron inside out.</div>',
     'marigold-trench-coat-01.jpg',
     'marigold-trench-coat-02.jpg',
     'marigold-trench-coat-03.jpg',
     'marigold-trench-coat-04.jpg',
     NULL,
     NULL,
     NULL,
     NULL,
     NULL,
     'MARIGOLD Kurtka Trench',
     '<div class="ju">Z kolekcji Consciously beautiful, ponadczasowy i klasyczny design z dbałością o szczegóły ukryte pod tym pięknie wykonanym płaszczem. Wykonany z materiału tencel, najdelikatniejszy w dotyku, zapewni Ci wygodę.  Guzik kokosowy z recyclingu doskonale wygląda z całościowym wyglądem. Przejściowy projekt trenczu MARIGOLD przyda się w niepewnych wietrznych warunkach pogodowych. Klasyka nigdy nie wychodzi z mody, prawda?</div>',
     '<div class="ju">100% tencel, celuloza drzewna, barwiony przy użyciu barwników z certyfikatem GOTS z certyfikatem GOTS, wyprodukowany w Turcji. Prać na delikatnym cyklu w 30 stopniach, prasować na niskim poziomie i nie suszyć w suszarce. Nasze tkaniny są trwałe i nie wymagają czyszczenia na sucho. Prasowac na lewej stronie.</div>'
   ),
   (
     'helen-blazer',
     'Available',
     false,
     'HELEN Blazer',
     'Dusty Rose',
     225,
     '<div class="ju">Consciously Beautiful collection, crafted with organic cotton and lotus fiber, made by supported woman in Cambodia. Are you looking for the perfect piece which is timeless and never goes out of style? You can be sure that HELEN blazer will be your forever loved piece in your wardrobe. Amazing fabric, beautiful feminine design will keep company to any basics layered underneath it. Sophisticated in classic and comfortable style. We love it! Additionally HELEN blazer is designed with usable two pockets at the front. That is not all, because the cut will also slim you down and mark your silhouette thanks to our pattern. Additionally HELEN have attached the most beautiful hand crafted rose made from the same material, which you can unfasten any time you need.</div>',
     '<div class="ju">95% cotton and 5% lotus flower beautifully woven fabric, using natural dyes, not certified. Unique and hand-woven by women in Cambodia. Wash on a gentle cycle at 30 degrees Celsius, iron on a low level and do not tumble dry. Our fabrics are durable and do not require dry cleaning.</div>',
     'helen-blazer-01.jpg',
     'helen-blazer-02.jpg',
     'helen-blazer-03.jpg',
     'helen-blazer-04.jpg',
     NULL,
     NULL,
     NULL,
     NULL,
     NULL,
     'HELEN Marynarka',
     '<div class="ju">Z kolekcji Consciously beautiful, wykonana z bawełny organicznej i włókna lotosu, stworzona przez wspierane kobiety z Kambodży. Szukasz idealnego ubrania, które jest ponadczasowe i nigdy nie wychodzi z mody? Możesz być pewien, że marynarka HELEN będzie Twoim ukochanym elementem Twojej garderoby. Niesamowita tkanina, piękny kobiecy design dotrzyma towarzystwa wszystkim podstawom ułożonym pod spodem. Wyrafinowany w klasycznym i wygodnym stylu. Ukochana! Dodatkowo nasza marynarka HELEN posiada nadające się do użytku dwie kieszenie z przodu. To nie wszystko, bo fason dodatkowo wysmukli i podkreśli sylwetkę dzięki naszemu wzorowi. Dodatkowo do HELEN dołączyłamy najpiękniejszą ręcznie wykonaną różę z tego samego materiału, którą w każdej chwili możesz odpiąć.</div>',
     '<div class="ju">95% bawełna i 5% włókna kwiata lotusa, pięknie tkana tkanina, przy użyciu naturalnych barwników, nie atestowana. Unikalne i ręcznie tkane przez kobiety w Kambodży. Prać w delikatnym cyklu w 30 stopniach Celsjusza, prasować na niskim poziomie i nie suszyć w suszarce. Nasze tkaniny są trwałe i nie wymagają czyszczenia na sucho.</div>'
   ),
   (
     'peri-sis-handkerchief',
     'Available',
     true,
     'PERI SIS Handkerchief',
     'Dusty Rose',
     27,
     '<div class="ju">PERI SIS handkerchief is a cute accent to the whole set. Finished with a cord of embroidery imitating the pearls of the beautiful plant String of Pearls. PERI SIS delights with its sensuality and delicacy, it will fit perfectly wrapted around your hand, neck or even as a addition  to your pocket as a styling accessory.<br /><br />Combine with the PERI blouse for a unique, monochrome look or with the REEVA jacket for a refreshing style. Made with care in Poland.<br /><br />PERI SIS handkerchief is made to order and can work 1-2 weeks before being hand sewn with care in Poland.</div>',
     '<div class="ju">100% organic cotton voile, GOTS certified, made in Turkey. Wash on delicate cycle at 30 celsius degrees, iron at low setting and do not tumble dry. Our fabrics are sustainable and do not require dry cleaning.</div>',
     'peri-sis-handkerchief-01.jpg',
     'peri-sis-handkerchief-02.jpg',
     'peri-sis-handkerchief-03.jpg',
     'peri-sis-handkerchief-04.jpg',
     NULL,
     NULL,
     NULL,
     NULL,
     NULL,
     'PERI SIS Chusteczka',
     '<div class="ju">Chusteczka PERI SIS jest ciekawym dopełnieniem do całości zestawu . Wykończona ręcznie haftem imitujący sznur perełek orginalnej rośliny Starzec Rowleya. PERI SIS zachwyca swoja zmysłowością i delikatnością, doskonale wkomponuje się przwiązana we włosy, na dłoni, szyji lub nawet w kieszeni jako dodatkowy detal stylizacji.<br /><br />Połącz z bluzka PERI aby uzyskać wyjątkowy, monochromatyczny wygląd lub z kurtka REEVA odświeżajac styl . Wykonana z dbałością w Polsce.<br /><br />PERI SIS chusteczka jest szyta i haftowana na zamówienie i może zająć 1-2 tygodnie, zanim zostanie ręcznie uszyta z dbałoscią w Polsce.</div>',
     '<div class="ju">100% woal z bawełny organicznej, z certyfikatem GOTS, wyprodukowany w Turcji. Prać w delikatnym cyklu w 30 stopniach, prasować na niskich obrotach i nie suszyć w suszarce.</div>'
   )
   ON CONFLICT (idname) DO UPDATE SET
   availability            = EXCLUDED.availability,
   is_one_size             = EXCLUDED.is_one_size,
   productname             = EXCLUDED.productname,
   productcolor            = EXCLUDED.productcolor,
   productprice            = EXCLUDED.productprice,
   desclong                = EXCLUDED.desclong,
   comp_care               = EXCLUDED.comp_care,
   pic1                    = EXCLUDED.pic1,
   pic2                    = EXCLUDED.pic2,
   pic3                    = EXCLUDED.pic3,
   pic4                    = EXCLUDED.pic4,
   pic5                    = EXCLUDED.pic5,
   pic6                    = EXCLUDED.pic6,
   pic7                    = EXCLUDED.pic7,
   pic8                    = EXCLUDED.pic8,
   pic9                    = EXCLUDED.pic9,
   name_pl                 = EXCLUDED.name_pl,
   desc_pl                 = EXCLUDED.desc_pl,
   composition_and_care_pl = EXCLUDED.composition_and_care_pl
   ;


INSERT INTO public.stock (idname, xs, s, m, ml, l, one_size) VALUES
 ('tuli-dress'                , 5, 5, 5, 5, 5, NULL),
 ('leya-wrap-dress'           , 5, 5, 5, 5, 5, NULL),
 ('dalhia-blouse'             , 5, 5, 5, 5, 5, NULL),
 ('bella-hand-painted-blouse' , 5, 5, 5, 5, 5, NULL),
 ('bella-blouse'              , 5, 5, 5, 5, 5, NULL),
 ('iris-vest'                 , 5, 5, 5, 5, 5, NULL),
 ('lili-top-satin'            , 5, 5, 5, 5, 5, NULL),
 ('lisia-dress'               , 5, 5, 5, 5, 5, NULL),
 ('dahlia-blouse'             , 5, 5, 5, 5, 5, NULL),
 ('senna-skirt'               , 5, 5, 5, 5, 5, NULL),
 ('delphi-culottes'           , 5, 5, 5, 5, 5, NULL),
 ('reeva-denim-jacket'        , 5, 5, 5, 5, 5, NULL),
 ('tilia-blouse'              , 5, 5, 5, 5, 5, NULL),
 ('lola-oversized-shirt'      , 5, 5, 5, 5, 5, NULL),
 ('peri-blouse'               , 5, 5, 5, 5, 5, NULL),
 ('flora-wrap-dress'          , 5, 5, 5, 5, 5, NULL),
 ('marigold-trench-coat'      , 5, 5, 5, 5, 5, NULL),
 ('helen-blazer'              , 5, 5, 5, 5, 5, NULL),
 ('peri-sis-handkerchief'     , NULL, NULL, NULL, NULL, NULL, 5)
 ON CONFLICT (idname) DO UPDATE SET
 xs = EXCLUDED.xs,
 s = EXCLUDED.s,
 m = EXCLUDED.m,
 ml = EXCLUDED.ml,
 l = EXCLUDED.l,
 one_size = EXCLUDED.one_size
 ;
