INSERT INTO public.products (idname, availability, is_one_size, productname, productcolor, productprice, desclong, comp_care, pic1, pic2, pic3, pic4, pic5, pic6, pic7, pic8, pic9, name_pl,  desc_pl,  composition_and_care_pl) VALUES
   (
     'leila-shirt',
     'Available',
     false,
     'LEILA Shirt',
     'Ocean Blue',
     165,
     '<div class="ju">100% linen quality oversize style with pocket at the front of the shirt. LEILA oversize shirt surprises with longer back and beautifully drapes the shirt. Timeless and versatile look from our capsule collection. Wear it together with VIOLA dress or SARI denim shorts.  Sustainably made with love in Europe by local tailors.</div>',
     '<div class="ju">Oeko-text certified 100% soft linen from Poland. Wash on a gentle cycle at 30 degrees, iron on a low level and do not tumble dry. Our fabrics are durable and do not require dry cleaning. Iron inside out.</div>',
     'leila-shirt-1.jpg',
     'leila-shirt-2.jpg',
     'leila-shirt-3.jpg',
     'leila-shirt-4.jpg',
     NULL,
     NULL,
     NULL,
     NULL,
     NULL,
     'LEILA Shirt',
     '<div class="ju">100% linen quality oversize style with pocket at the front of the shirt. LEILA oversize shirt surprises with longer back and beautifully drapes the shirt. Timeless and versatile look from our capsule collection. Wear it together with VIOLA dress or SARI denim shorts.  Sustainably made with love in Europe by local tailors.</div>',
     '<div class="ju">Oeko-text certified 100% soft linen from Poland. Wash on a gentle cycle at 30 degrees, iron on a low level and do not tumble dry. Our fabrics are durable and do not require dry cleaning. Iron inside out.</div>'
   ),
   (
     'viola-dress',
     'Available',
     false,
     'VIOLA Dress',
     'Ocean Blue',
     180,
     '<div class="ju">100% organic cotton jersey dress.  Middle length and comfortable fit dress will flatter your silhouette thanks to loose fit and waist cut with elastic band. VIOLA surprises with extra pockets on the side of the dress for your comfort. Timeless look and easy to wear dress will be your favorite choice from your capsule  wardrobe. Sustainably made with love in Europe by local tailors.</div>',
     '<div class="ju">Wonderfully soft organic jersey fabric made of 100% pure organic cotton, GOTS certified. 100% pure organic cotton - for all who do not like synthetic fiber spandex on the skin !!! This organic fabric is certified by the Global Organic Textile Standard (GOTS) from the cotton fiber to the knitting, the dyeing to our counter. Wash on a gentle cycle at 30 degrees, iron on a low level and do not tumble dry. Our fabrics are durable and do not require dry cleaning. Iron inside out.</div>',
     'viola-dress-1.jpg',
     'viola-dress-2.jpg',
     'viola-dress-3.jpg',
     'viola-dress-4.jpg',
     NULL,
     NULL,
     NULL,
     NULL,
     NULL,
     'VIOLA Dress',
     '<div class="ju">100% organic cotton jersey dress.  Middle length and comfortable fit dress will flatter your silhouette thanks to loose fit and waist cut with elastic band. VIOLA surprises with extra pockets on the side of the dress for your comfort. Timeless look and easy to wear dress will be your favorite choice from your capsule  wardrobe. Sustainably made with love in Europe by local tailors.</div>',
     '<div class="ju">Wonderfully soft organic jersey fabric made of 100% pure organic cotton, GOTS certified. 100% pure organic cotton - for all who do not like synthetic fiber spandex on the skin !!! This organic fabric is certified by the Global Organic Textile Standard (GOTS) from the cotton fiber to the knitting, the dyeing to our counter. Wash on a gentle cycle at 30 degrees, iron on a low level and do not tumble dry. Our fabrics are durable and do not require dry cleaning. Iron inside out.</div>'
   ),
   (
     'susan-dress',
     'Available',
     false,
     'SUSAN Dress',
     'Vivid Brown',
     250,
     '<div class="ju">100% organic tencel middle length dress. Loose fit design perfectly flatters your silhouette thanks to well design pattern. Additionally  SUSAN dress surprises with extra hidden pockets on the side of the dress and embroidery from our inspiration. Longer cleavage at the front and the back of the dress creates feminine approach to our design. Our design it’s a perfect combination where elegant look meets comfort and feminine style.  Sustainably made with love in Europe by local tailors.</div>',
     '<div class="ju">100% Tencel, wood cellulose, dyed with GOTS certificate (Global Organization Textile Standards), made in Turkey. Wash on a gentle cycle at 30 degrees, iron on a low level and do not tumble dry. Our fabrics are durable and do not require dry cleaning. Iron inside out.</div>',
     'susan-dress-1.jpg',
     'susan-dress-2.jpg',
     'susan-dress-3.jpg',
     'susan-dress-4.jpg',
     NULL,
     NULL,
     NULL,
     NULL,
     NULL,
     'SUSAN Dress',
     '<div class="ju">100% organic tencel middle length dress. Loose fit design perfectly flatters your silhouette thanks to well design pattern. Additionally  SUSAN dress surprises with extra hidden pockets on the side of the dress and embroidery from our inspiration. Longer cleavage at the front and the back of the dress creates feminine approach to our design. Our design it’s a perfect combination where elegant look meets comfort and feminine style.  Sustainably made with love in Europe by local tailors.</div>',
     '<div class="ju">100% Tencel, wood cellulose, dyed with GOTS certificate (Global Organization Textile Standards), made in Turkey. Wash on a gentle cycle at 30 degrees, iron on a low level and do not tumble dry. Our fabrics are durable and do not require dry cleaning. Iron inside out.</div>'
   ),
   (
     'deli-shorts',
     'Available',
     false,
     'DELI Shorts',
     'Vivid Brown',
     95,
     '<div class="ju">100% organic tencel shorts. High wast and very comfortable style thanks to pattern and divine quality. Perfect cut and velvety soft tencel fabric provide natural comfort. Beautifully finished and timeless cut. Beloved piece in you capsule wardrobe. Sustainably made with love in Europe by local tailors.</div>',
     '<div class="ju">100% Tencel, wood cellulose, dyed with GOTS certified dyes with GOTS certificate (Global Organization Textile Standards), made in Turkey. Wash on a gentle cycle at 30 degrees, iron on a low level and do not tumble dry. Our fabrics are durable and do not require dry cleaning. Iron inside out.</div>',
     'deli-shorts-1.jpg',
     'deli-shorts-2.jpg',
     'deli-shorts-3.jpg',
     'deli-shorts-4.jpg',
     NULL,
     NULL,
     NULL,
     NULL,
     NULL,
     'DELI Shorts',
     '<div class="ju">100% organic tencel shorts. High wast and very comfortable style thanks to pattern and divine quality. Perfect cut and velvety soft tencel fabric provide natural comfort. Beautifully finished and timeless cut. Beloved piece in you capsule wardrobe. Sustainably made with love in Europe by local tailors.</div>',
     '<div class="ju">100% Tencel, wood cellulose, dyed with GOTS certified dyes with GOTS certificate (Global Organization Textile Standards), made in Turkey. Wash on a gentle cycle at 30 degrees, iron on a low level and do not tumble dry. Our fabrics are durable and do not require dry cleaning. Iron inside out.</div>'
   ),
   (
     'sari-denim-shorts',
     'Available',
     false,
     'SARI Denim Shorts',
     'Satin Cream',
     90,
     '<div class="ju">100% organic cotton denim. High wast and non stretchy denim sustainably made for your capsule wardrobe. Beautifully tailored, classic and stylish, without elastan, like it used to be. The timeless and simple cut of SARI will change your style from a relaxed to even elegant style that you create for yourself for years. Sustainably made with love in Europe by local tailors.</div>',
     '<div class="ju">100% organic cotton woven denim, GOTS certified (Global Organization Textile Standards), made in Turkey. Wash in a regular cycle at 30 degrees Celsius, iron on a low level and do not tumble dry. Our fabrics are durable and do not require dry cleaning.</div>',
     'sari-denim-shorts-1.jpg',
     'sari-denim-shorts-2.jpg',
     'sari-denim-shorts-3.jpg',
     'sari-denim-shorts-4.jpg',
     NULL,
     NULL,
     NULL,
     NULL,
     NULL,
     'SARI Denim Shorts',
     '<div class="ju">100% organic cotton denim. High wast and non stretchy denim sustainably made for your capsule wardrobe. Beautifully tailored, classic and stylish, without elastan, like it used to be. The timeless and simple cut of SARI will change your style from a relaxed to even elegant style that you create for yourself for years. Sustainably made with love in Europe by local tailors.</div>',
     '<div class="ju">100% organic cotton woven denim, GOTS certified (Global Organization Textile Standards), made in Turkey. Wash in a regular cycle at 30 degrees Celsius, iron on a low level and do not tumble dry. Our fabrics are durable and do not require dry cleaning.</div>'
   ),
   (
     'adel-jacket',
     'Available',
     false,
     'ADEL Jacket',
     'Satin Cream',
     190,
     '<div class="ju">100% organic denim. Oversize denim jacket with feminine and smooth details. Designed for light, elegant, yet comfortable look. Additionally ADEL jacket has co-friendly, sustainable buttons from corozo nuts. Pair it with our SARI denim shorts or CALLA denim long jeans for monochrome style. Sustainably made with love in Europe by local tailors.</div>',
     '<div class="ju">100% organic cotton woven denim, GOTS certified (Global Organization Textile Standards), made in Turkey. Wash in a regular cycle at 30 degrees Celsius, iron on a low level and do not tumble dry. Our fabrics are durable and do not require dry cleaning.</div>',
     'adel-jacket-1.jpg',
     'adel-jacket-2.jpg',
     'adel-jacket-3.jpg',
     'adel-jacket-4.jpg',
     NULL,
     NULL,
     NULL,
     NULL,
     NULL,
     'ADEL Jacket',
     '<div class="ju">100% organic denim. Oversize denim jacket with feminine and smooth details. Designed for light, elegant, yet comfortable look. Additionally ADEL jacket has co-friendly, sustainable buttons from corozo nuts. Pair it with our SARI denim shorts or CALLA denim long jeans for monochrome style. Sustainably made with love in Europe by local tailors.</div>',
     '<div class="ju">100% organic cotton woven denim, GOTS certified (Global Organization Textile Standards), made in Turkey. Wash in a regular cycle at 30 degrees Celsius, iron on a low level and do not tumble dry. Our fabrics are durable and do not require dry cleaning.</div>'
   ),
   (
     'raisa-dress',
     'Available',
     false,
     'RAISA Dress',
     'Satin Cream',
     260,
     '<div class="ju">100% organic cotton middlenght dress. Loose fit with long cleavage creates comfortable and feminine design at the same time. Embroidery on the top of the dress, designed by our creative designer Justyna.  Details from our inspiration gives an extra unique approach to our beloved and timeless collection peace and to your capsule wardrobe. RAISA dress additionally has 2 side pockets for your comfort. Sustainably made with love in Europe by local tailors.</div>',
     '<div class="ju">100% organic cotton voile, GOTS certified (Global Organization Textile Standards), made in Turkey. Wash on delicate cycle at 30 celsius degrees, iron at low setting and do not tumble dry. Our fabrics are sustainable and do not require dry cleaning.</div>',
     'raisa-dress-1.jpg',
     'raisa-dress-2.jpg',
     'raisa-dress-3.jpg',
     'raisa-dress-4.jpg',
     NULL,
     NULL,
     NULL,
     NULL,
     NULL,
     'RAISA Dress',
     '<div class="ju">100% organic cotton middlenght dress. Loose fit with long cleavage creates comfortable and feminine design at the same time. Embroidery on the top of the dress, designed by our creative designer Justyna.  Details from our inspiration gives an extra unique approach to our beloved and timeless collection peace and to your capsule wardrobe. RAISA dress additionally has 2 side pockets for your comfort. Sustainably made with love in Europe by local tailors.</div>',
     '<div class="ju">100% organic cotton voile, GOTS certified (Global Organization Textile Standards), made in Turkey. Wash on delicate cycle at 30 celsius degrees, iron at low setting and do not tumble dry. Our fabrics are sustainable and do not require dry cleaning.</div>'
   ),
   (
     'lilium-trousers',
     'Available',
     false,
     'LILIUM Trousers',
     'Satin Cream',
     180,
     '<div class="ju">Made from 100% organic very soft cotton. LILIUM trousers are perfectly designed for effortless design and still comfortable style. Loose fit pattern with elastic band on the sides and two pockets will be ever most beloved trousers in your capsule wardrobe at summer . Sustainably made with love in Europe by local tailors.</div>',
     '<div class="ju">Made of 100% certified organic cotton, GOTS certified (Global Organization Textile Standards), Lightweight, double-layer organic muslin, free from microplastics, 100% biodegradable. Wash on delicate cycle at 30 celsius degrees, iron at low setting and do not tumble dry. Our fabrics are sustainable and do not require dry cleaning.</div>',
     'lilium-trousers-1.jpg',
     'lilium-trousers-2.jpg',
     'lilium-trousers-3.jpg',
     'lilium-trousers-4.jpg',
     NULL,
     NULL,
     NULL,
     NULL,
     NULL,
     'LILIUM Trousers',
     '<div class="ju">Made from 100% organic very soft cotton. LILIUM trousers are perfectly designed for effortless design and still comfortable style. Loose fit pattern with elastic band on the sides and two pockets will be ever most beloved trousers in your capsule wardrobe at summer . Sustainably made with love in Europe by local tailors.</div>',
     '<div class="ju">Made of 100% certified organic cotton, GOTS certified (Global Organization Textile Standards), Lightweight, double-layer organic muslin, free from microplastics, 100% biodegradable. Wash on delicate cycle at 30 celsius degrees, iron at low setting and do not tumble dry. Our fabrics are sustainable and do not require dry cleaning.</div>'
   ),
   (
     'neeja-top',
     'Available',
     false,
     'NEEJA Top',
     'Satin Cream',
     140,
     '<div class="ju">Made from 100% organic very soft cotton. NEEJA top specially designed for comfortable style and feminine design with cleavage at the front and back of the top. Pair it up with LILIUM trousers for monochrome and uniform look. Elegant design, comfortable style and feminine essence is what stands out from our timeless collection pieces. Sustainably made with love in Europe by local tailors.</div>',
     '<div class="ju">Made of 100% certified organic cotton, GOTS certified (Global Organization Textile Standards), Lightweight, double-layer organic muslin, free from microplastics, 100% biodegradable. Wash on delicate cycle at 30 celsius degrees, iron at low setting and do not tumble dry. Our fabrics are sustainable and do not require dry cleaning.</div>',
     'neeja-top-1.jpg',
     'neeja-top-2.jpg',
     'neeja-top-3.jpg',
     'neeja-top-4.jpg',
     NULL,
     NULL,
     NULL,
     NULL,
     NULL,
     'NEEJA Top',
     '<div class="ju">Made from 100% organic very soft cotton. NEEJA top specially designed for comfortable style and feminine design with cleavage at the front and back of the top. Pair it up with LILIUM trousers for monochrome and uniform look. Elegant design, comfortable style and feminine essence is what stands out from our timeless collection pieces. Sustainably made with love in Europe by local tailors.</div>',
     '<div class="ju">Made of 100% certified organic cotton, GOTS certified (Global Organization Textile Standards), Lightweight, double-layer organic muslin, free from microplastics, 100% biodegradable. Wash on delicate cycle at 30 celsius degrees, iron at low setting and do not tumble dry. Our fabrics are sustainable and do not require dry cleaning.</div>'
   )
   ON CONFLICT (idname) DO UPDATE SET
   availability            = EXCLUDED.availability,
   is_one_size             = EXCLUDED.is_one_size,
   productname             = EXCLUDED.productname,
   productcolor            = EXCLUDED.productcolor,
   productprice            = EXCLUDED.productprice,
   desclong                = EXCLUDED.desclong,
   comp_care               = EXCLUDED.comp_care,
   pic1                    = EXCLUDED.pic1,
   pic2                    = EXCLUDED.pic2,
   pic3                    = EXCLUDED.pic3,
   pic4                    = EXCLUDED.pic4,
   pic5                    = EXCLUDED.pic5,
   pic6                    = EXCLUDED.pic6,
   pic7                    = EXCLUDED.pic7,
   pic8                    = EXCLUDED.pic8,
   pic9                    = EXCLUDED.pic9,
   name_pl                 = EXCLUDED.name_pl,
   desc_pl                 = EXCLUDED.desc_pl,
   composition_and_care_pl = EXCLUDED.composition_and_care_pl
   ;


INSERT INTO public.stock
 (idname,              xs, s, m, ml, l, one_size) VALUES
 ('leila-shirt',       5,  5, 5, 5,  5, NULL),
 ('viola-dress',       5,  5, 5, 5,  5, NULL),
 ('susan-dress',       5,  5, 5, 5,  5, NULL),
 ('deli-shorts',       5,  5, 5, 5,  5, NULL),
 ('sari-denim-shorts', 5,  5, 5, 5,  5, NULL),
 ('adel-jacket',       5,  5, 5, 5,  5, NULL),
 ('raisa-dress',       5,  5, 5, 5,  5, NULL),
 ('lilium-trousers',   5,  5, 5, 5,  5, NULL),
 ('neeja-top',         5,  5, 5, 5,  5, NULL)
 ON CONFLICT (idname) DO UPDATE SET
 xs       = EXCLUDED.xs,
 s        = EXCLUDED.s,
 m        = EXCLUDED.m,
 ml       = EXCLUDED.ml,
 l        = EXCLUDED.l,
 one_size = EXCLUDED.one_size
 ;
