# This config uses the `.circleci/extended/orb-test.yml` as its base, and then publishes the app to S3.
# The workflow contained here demonstrates a practical application of `post-steps`
# and using workspace persistence
version: 2.1


orbs:
  node: circleci/node@4.1
  aws-s3: circleci/aws-s3@2.0

jobs:
  runTests:
    docker:
      - image: circleci/node:14
      - image: mysql:5.7.23
        environment:
          MYSQL_RANDOM_ROOT_PASSWORD: true
          MYSQL_DATABASE: myna_test
          MYSQL_USER: myna_test
          MYSQL_PASSWORD: test
    steps:
      - checkout
      - run:
          name: Waiting for MySQL to be ready
          command: |
            for i in `seq 1 10`;
            do
              nc -z 127.0.0.1 3306 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for MySQL && exit 1
      - run:
          name: Install MySQL CLI; Import dummy data; run an example query
          command: |
            sudo apt-get install default-mysql-client
            mysql -h 127.0.0.1 -u myna_test -ptest myna_test < sql-data/schema.sql
      - run: npm ci --no-audit
      - run: npm test

workflows:
  sample:
    jobs:
      - runTests
